### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by pksunkara**

### CODE REVIEW

**Comment by w-vi** [comment]
Shouldn't the commit message be "chore: update ..."?

**Comment by w-vi** [comment]
And also it does more than just updating travis it also updates dependencies, si I'd say two commits

**Comment by pksunkara** [comment]
Those are just development dependencies. No need for new commit.

**Comment by w-vi** [comment]
still the commit message is not according to the rules we have or is it?

**Comment by pksunkara** [comment]
Updated.

**Review by w-vi — APPROVED** [review]

**Pull request merged**
