### PR TITLE
fix(dependencies): use peerDependencies for protagonist

### PR DESCRIPTION
**Pull request by JackuB**
This will skip protagonist installation when not required - https://docs.npmjs.com/files/package.json#peerdependencies

### CODE REVIEW

**Comment by honzajavorek** [comment]
What does "when not required" mean in practice?

**Comment by JackuB** [comment]
@honzajavorek You will have to explicitly install protagonist. Peer is not installing it by default for you. Optional will install it always.

**Comment by honzajavorek** [comment]
So if you're using Dredd and you want to be able to parse API Blueprint efficiently, you should do

```
$ npm install dredd protagonist --save-dev
```

As opposed to:

```
$ npm install dredd --save-dev
```

Which would be useful for cases when:

- You only use Swagger
- You use API Blueprint, but you don't need the performance

Is that correct?

**Comment by pksunkara** [comment]
Yes

**Comment by JackuB** [comment]
Afaik drafter.js is not "that" slower anymore

**Comment by kylef** [comment]
Does the dependency that is depending on `drafter`  have to have the peer dependency? For example in the following tree:

```
└── dredd
    └── fury-adapter-apib-parser
        ├── drafter
        │   └── drafter.js
        └── protagonist
```

Is the following permitted (where the peer doing the dependency on Protagonist is multiple levels away):?

```
├── dredd
│   └── fury-adapter-apib-parser
│       └── drafter
│           └── drafter.js
└── protagonist
```

#### Current tree (for reference)

```
└── dredd
    └── fury-adapter-apib-parser
        └── drafter
            ├── drafter.js
            └── protagonist
```

**Comment by kylef** [comment]
This will be a breaking change so please add `BREAKING CHANGE` to the commit message as per commitizen (`fix(dependencies): use peerDependencies for protagonist`). The test failures are due to the tests that ensure Protagonist is optionally installed when the environment allows.

**Comment by kylef** [comment]
> Afaik drafter.js is not "that" slower anymore

It's around six times slower at the moment, if you have a blueprint that takes ~10-20 seconds to parse it's likely to then take one to two minutes with drafter.js.

> Average JS speed: 5.4 times slower than Protagonist

**Comment by honzajavorek** [comment]
Note it's not `BREAKING CHANGE`, but `BREAKING CHANGE:` - I burned myself once already not having the colon in place 🙄

**Comment by honzajavorek** [comment]
I can imagine Dredd working in a similar way as things using `redis` / `hiredis` or various `json` libraries in the Python world. Basically, the performance would be opt-in. Also, not all users of Dredd are using API Blueprint and those have the compilation penalty by default right now. They don't even know yet they like Dredd, they've never seen its docs, and on first installation, they get long install or they need to opt-out from it explicitly. I think that's not ideal experience.

So 👍 for opt-in to parser performance. I'm more keen to explain people how to get faster API Blueprint parser, explicitly, than to have every single person installing Dredd watching endless installs during their first time experience or beginner usage.

**Review by pksunkara — DISMISSED** [review]

**Comment by JackuB** [comment]
Closing in favor of #16

**Pull request closed without merging**
